Repository TBD-Labs-AI/latched, pull requests merged in 2024-09, with the labels that each got.

#6 Minor change
  pyproject.toml
Labels: 🛠️ environments, 🔧 refactoring

#14 Fix typo
  examples/Phi3.5-mini-instruct-to-CoreML/main.py
Labels: bug

#12 Docs/readme.md
  CONTRIBUTING.md
  Images/Latched-Banner.png
  Images/Logo-no-background-3x.png
  Images/Logo-nobackground.png
  Images/discord-logo.svg
  README.md
Labels: documentation

#16 Refactoring
  poetry.lock
  pyproject.toml
  src/latched/model_optimizers/auto.py
  src/latched/model_optimizers/base.py
  src/latched/model_optimizers/ptq/hf_qint8.py
  src/latched/model_wrappers/auto.py
Labels: bug, 🛠️ environments

#17 Edit optimization and README.md
  README.md
  src/latched/model_optimizers/ptq/omni_quant.py
  src/latched/model_optimizers/ptq/smooth_quant.py
  src/latched/model_optimizers/qat/llm_qat.py
Labels: bug, documentation

#28 Add openvino, onix export
  examples/llama-3.1-8B-Instruct-to-onnx/llama_onnx_example.py
  examples/llama-3.1-8B-Instruct-to-openvino/llama_openvino_example.py
  examples/phi-3.5-mini-to-onnx/phi_3.5_onnx_example.py
  poetry.lock
  pyproject.toml
  src/latched/endpoints/accelerators/intel/__init__.py
  src/latched/endpoints/accelerators/intel/gaudi.py
  src/latched/endpoints/accelerators/intel/xeon.py
  src/latched/endpoints/accelerators/rebellion/__init__.py
  src/latched/endpoints/accelerators/rebellion/atom.py
  src/latched/endpoints/base.py
  src/latched/endpoints/edge_devices/nvidia/__init__.py
  src/latched/endpoints/edge_devices/nvidia/jetson_nano_orin.py
  src/latched/endpoints/edge_devices/qualcomm/__init__.py
  src/latched/endpoints/edge_devices/qualcomm/snapdragon.py
  src/latched/endpoints/intel.py
  src/latched/endpoints/nvidia.py
  src/latched/endpoints/qualcomm.py
  src/latched/endpoints/rebellion.py
  src/latched/model_exporters/onnx.py
  src/latched/model_exporters/openvino.py
  src/latched/model_optimizers/torchao.py
  src/latched/model_wrappers/huggingface.py
Labels: enhancement, 🛠️ environments
